version: '3.0'

services:
  test:
    environment:
      - ENVIRONMENT=development
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: /app/.venv/bin/pytest
    depends_on:
      - "db"

  type-check:
    environment:
      - ENVIRONMENT=development
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: /app/.venv/bin/mypy app tests

  db:
    image: redis:6-alpine
